#!/usr/bin/env python3
"""Generate embedded shell completion sources for beez --install-completion."""

from __future__ import annotations

import sys
from pathlib import Path

FILES = (
    "beez.bash",
    "beez.zsh",
    "activate.bash",
    "activate.zsh",
    "install-lib.sh",
)

SYMBOLS = {
    "beez.bash": "kEmbeddedBeezBash",
    "beez.zsh": "kEmbeddedBeezZsh",
    "activate.bash": "kEmbeddedActivateBash",
    "activate.zsh": "kEmbeddedActivateZsh",
    "install-lib.sh": "kEmbeddedInstallLib",
}


def c_string_literal(content: str) -> str:
    chunks: list[str] = []
    current: list[str] = ['"']

    for character in content:
        if character == "\\":
            current.append("\\\\")
        elif character == '"':
            current.append('\\"')
        elif character == "\n":
            current.append("\\n")
        elif ord(character) < 32 or ord(character) == 127:
            current.append(f"\\x{ord(character):02x}")
        else:
            current.append(character)

        if len(current) >= 1000:
            current.append('"')
            chunks.append("".join(current))
            current = ['"']

    current.append('"')
    chunks.append("".join(current))
    return "\n    ".join(chunks)


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: generate-completion-embedded.py <source-dir> <output.cpp>", file=sys.stderr)
        return 1

    source_dir = Path(sys.argv[1])
    output_cpp = Path(sys.argv[2])

    lines = [
        "// Generated by scripts/generate-completion-embedded.py",
        '#include "beez/cli/completion_embedded.hpp"',
        "",
        "#include <array>",
        "#include <string_view>",
        "",
        "namespace beez::cli",
        "{",
        "namespace",
        "{",
        "",
    ]

    for filename in FILES:
        content = (source_dir / filename).read_text(encoding="utf-8")
        symbol = SYMBOLS[filename]
        lines.extend(
            [
                f"constexpr std::string_view {symbol} =",
                f"    {c_string_literal(content)};",
                "",
            ]
        )

    lines.extend(
        [
            "} // namespace",
            "",
            "std::array<EmbeddedCompletionFile, 5> embeddedCompletionFiles()",
            "{",
            "    return {",
        ]
    )

    for filename in FILES:
        lines.append(
            f'        EmbeddedCompletionFile{{"{filename}", {SYMBOLS[filename]}}},'
        )

    lines.extend(
        [
            "    };",
            "}",
            "",
            "} // namespace beez::cli",
            "",
        ]
    )

    output_cpp.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
