find_program(CCACHE_EXE NAMES "ccache")
find_program(SCCACHE_EXE NAMES "sccache")

if(BUILD_CACHE)
    if(SCCACHE_EXE)
        message(STATUS "Using sccache: ${SCCACHE_EXE}")
        set(CMAKE_CXX_COMPILER_LAUNCHER "${SCCACHE_EXE}")
        set(CMAKE_C_COMPILER_LAUNCHER "${SCCACHE_EXE}")
    elseif(CCACHE_EXE)
        message(STATUS "Using ccache: ${CCACHE_EXE}")
        set(CMAKE_CXX_COMPILER_LAUNCHER "${CCACHE_EXE}")
        set(CMAKE_C_COMPILER_LAUNCHER "${CCACHE_EXE}")
    else()
        message(STATUS "No build cache tool found (ccache/sccache)")
    endif()
else()
    message(STATUS "Build cache disabled")
endif()
